### ISSUE TITLE
Добавление раздела Win

### ISSUE THREAD

**Issue by AdmAlexus** [learn-it-in-russian/tldr-ru#33]
Может быть добавить раздел Windows для "гребаных виндузятников"?
А то macOs - есть, SunOs - есть, а окошек - нет:)

**Comment by pashcovich** [comment]
правильно писать "гребаных вантузятников"

**Comment by AdmAlexus** [comment]
@pashcovich Обидно звучит. Чай не сантехники

**Comment by bugov** [comment]
Можно. Это выйдет за рамки проекта по переводу tldr, но я только за! Не спец в винде, поэтому нужна помощь, если за это берёмся.

**Comment by AdmAlexus** [comment]
@bugov Попробую накидать чего-нибудь неспешно...
Часть команд правда пересекается с разделом **common**
Их, я думаю, добавлять в раздел win не надо будет?

**Comment by pashcovich** [comment]
я думаю надо, так как ключи у многих команд в винде и линухе разные, как пример `-n` у `ping`

**Comment by bugov** [comment]
надо

**Comment by bugov** [comment]
Добавил https://900913.ru/tldr/windows/

**Comment by pashcovich** [comment]
ничоси, не прошло и пяти лет

**Comment by bugov** [comment]
@pashcovich Привет! Сам раздел добавился автоматом, ещё когда @AdmAlexus закоммитил assoc и ещё несколько утилит. А вчера я просто туда подтащил ещё кучу (на английском) - теперь и пользоваться/показать не стыдно.
