### ISSUE TITLE
-ru 

### ISSUE THREAD

**Issue by RedbHawk** [learn-it-in-russian/tldr-ru#63]
1. Смысл добавлять оригинальные md файлы, вы думаете для англичан мало инфы в инэте ? Лишняя работа. 
2. Сколько времени занимает добавление новых ru.md на сайт ?

**Comment by bugov** [comment]
1. Чтобы была возможность прочитать оригинал.
2. Минуты 2 - не заскриптовано, но ограничивается 5-6 командами.

**Comment by RedbHawk** [comment]
3. Не хватает жирного шрифта для акцентирования внимания на чём-то в md файлах. Легче усваивается.
К примеру [тут](https://900913.ru/tldr/common/ru/cowsay/) : 
Вывести ASCII корову **говорящую** "Hello world!".
Вывести **думающую** ASCII корову.
